"""Report and export utilities for coursework."""

from typing import Any, Dict, List, Optional

from ..utils.exceptions import ValidationError


def markdown_report(
    ticker: str,
    name: str,
    info: Dict,
    ratios: Dict[str, Any],
    *,
    sector: Optional[str] = None,
    sections: Optional[List[str]] = None,
) -> str:
    """
    Generate a Markdown equity snapshot for class submissions.
    """
    sections = sections or ["overview", "valuation", "profitability", "liquidity"]
    lines = [
        f"# {name} ({ticker}) — Financial Analysis Report",
        "",
        f"**Sector:** {sector or info.get('sector', 'N/A')}",
        f"**Industry:** {info.get('industry', 'N/A')}",
        f"**Current Price:** ${info.get('currentPrice', 'N/A')}",
        f"**Market Cap:** {info.get('marketCap', 'N/A')}",
        "",
    ]

    if "overview" in sections:
        desc = info.get("longBusinessSummary") or info.get("description") or ""
        if desc:
            lines.extend(
                ["## Overview", "", desc[:500] + ("..." if len(desc) > 500 else ""), ""]
            )

    if "valuation" in sections:
        lines.extend(
            [
                "## Valuation Ratios",
                "",
                f"| Ratio | Value |",
                f"|-------|-------|",
                f"| P/E | {ratios.get('pe', 'N/A')} |",
                f"| P/B | {ratios.get('pb', 'N/A')} |",
                f"| P/S | {ratios.get('ps', 'N/A')} |",
                f"| EV/EBITDA | {ratios.get('ev_ebitda', 'N/A')} |",
                "",
            ]
        )

    if "profitability" in sections:
        lines.extend(
            [
                "## Profitability",
                "",
                f"| Ratio | Value |",
                f"|-------|-------|",
                f"| ROE | {ratios.get('roe', 'N/A')} |",
                f"| ROA | {ratios.get('roa', 'N/A')} |",
                f"| ROIC | {ratios.get('roic', 'N/A')} |",
                f"| Profit Margin | {ratios.get('profit_margin', 'N/A')} |",
                "",
            ]
        )

    if "liquidity" in sections:
        lines.extend(
            [
                "## Liquidity & Leverage",
                "",
                f"| Ratio | Value |",
                f"|-------|-------|",
                f"| Current Ratio | {ratios.get('current_ratio', 'N/A')} |",
                f"| Quick Ratio | {ratios.get('quick_ratio', 'N/A')} |",
                f"| Debt/Equity | {ratios.get('debt_to_equity', 'N/A')} |",
                "",
            ]
        )

    lines.append("---")
    lines.append("*Generated by InvestorMate*")
    return "\n".join(lines)


def export_to_excel(
    path: str,
    *,
    ticker: str,
    info: Dict,
    ratios: Dict[str, Any],
    income_stmt: Optional[Dict] = None,
    balance_sheet: Optional[Dict] = None,
) -> str:
    """
    Export analysis workbook (requires openpyxl: pip install investormate[export]).
    """
    try:
        from openpyxl import Workbook
    except ImportError as exc:
        raise ValidationError(
            "Excel export requires openpyxl. Install with: pip install investormate[export]"
        ) from exc

    wb = Workbook()
    ws = wb.active
    ws.title = "Summary"
    ws.append(["Ticker", ticker])
    ws.append(["Name", info.get("shortName") or info.get("longName", "")])
    ws.append(["Price", info.get("currentPrice")])
    ws.append(["Market Cap", info.get("marketCap")])
    ws.append([])
    ws.append(["Ratio", "Value"])
    for k, v in ratios.items():
        if v is not None:
            ws.append([k, v])

    if income_stmt:
        ws2 = wb.create_sheet("Income Statement")
        periods = sorted(income_stmt.keys(), reverse=True)
        items = sorted({k for p in periods for k in income_stmt[p].keys()})
        ws2.append(["Line Item"] + periods)
        for item in items:
            ws2.append([item] + [income_stmt[p].get(item) for p in periods])

    if balance_sheet:
        ws3 = wb.create_sheet("Balance Sheet")
        periods = sorted(balance_sheet.keys(), reverse=True)
        items = sorted({k for p in periods for k in balance_sheet[p].keys()})
        ws3.append(["Line Item"] + periods)
        for item in items:
            ws3.append([item] + [balance_sheet[p].get(item) for p in periods])

    wb.save(path)
    return path
